# Rime schema
# encoding: utf-8

schema:
  schema_id: luna_pinyin
  name: 朙月拼音
  version: '1.0.0'
  author:
    - 佛振 <chen.sst@gmail.com>
  description: |
    Rime 預設的拼音輸入方案。

switches:
  - name: ascii_mode
    reset: 0
    states: [ 中文, 西文 ]
  - name: full_shape
    states: [ 半角, 全角 ]
  - name: simplification
    reset: 1
    states: [ 漢字, 汉字 ]
  - options: [ "gbk","utf8" ]
    reset: 0
    states: [ 通用, 增廣 ]

engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - table_translator@custom_phrase
    - reverse_lookup_translator
    - script_translator
  filters:
    - simplifier
    - uniquifier
    - charset_filter@gbk
    - charset_filter@utf-8

speller:
  alphabet: zyxwvutsrqponmlkjihgfedcba
  delimiter: "'"
  algebra:
    __patch:
      - pinyin:/zh_z_bufen
      - pinyin:/en_eng_bufen
      - pinyin:/abbreviation
      - pinyin:/spelling_correction
      - pinyin:/key_correction

translator:
  dictionary: luna_pinyin.extended
  preedit_format:
    - xform/([nl])v/$1ü/
    - xform/([nl])ue/$1üe/
    - xform/([jqxy])v/$1u/

custom_phrase:
  dictionary: ""
  user_dict: custom_phrase
  db_class: stabledb
  enable_completion: false
  enable_sentence: false
  initial_quality: 1

punctuator:
  import_preset: symbols

recognizer:
  import_preset: default
  patterns:
    punct: '^/([0-9]0?|[A-Za-z]+)$'
    reverse_lookup: "`[a-z]*'?$"

__patch:
  # 使用八股文語言模型
  - grammar:/hant?
  # 用家自選配置
  - luna_pinyin.custom:/patch?
